### ISSUE TITLE
Missing return-type annotations in qwPage and util

### ISSUE THREAD

**Issue by Tellus** [qualweb/types#3]
Compiling a project that depends on `@qualweb/types` fails if `noImplicitAny` is set to true in the TypeScript compiler configuration:

```
node_modules/@qualweb/types/qwPage.d.ts:6:12 - error TS7010: 'cacheValue', which lacks return-type annotation, implicitly has an 'any' return type.

6     public cacheValue(selector: string, method: string, value: string|undefined);
             ~~~~~~~~~~

node_modules/@qualweb/types/util.d.ts:48:21 - error TS7010: 'getValueFromEmbeddedControl', which lacks return-type annotation, implicitly has an 'any' return type.

48     export function getValueFromEmbeddedControl(element: QWElement, page: QWPage, treeSelector: string);
```

Simply setting their return types to `any` is sufficient to remove the error, but optimally they should have their correct return values set. Unfortunately, I don't know what those types are, off hand, so I was hoping maybe you could patch that :)

**Comment by joao-vicente** [comment]
Hi! Thanks for the information! I've patched it and it should be fixed now. Once you confirm it i'll close the issue

**Comment by Tellus** [comment]
Hi again.

That seems to have fixed it. Brilliant!

Quick closing note, for sake of completeness: The errors don't occur if `skipLibChecks` is set to `false` in `tsconfig.json`, since the TypeScript compiler will simply skip checking the definition files of dependency libraries. Maybe I was a bit "too" strict in our compiler configurations :-)

I only mention it since the recommended "base" configuration in [@tsconfig/recommended](https://www.npmjs.com/package/@tsconfig/recommended) ignores those lib checks, so there's a fair chance many users wouldn't have gotten the error at all.

Thanks for the quick reply - take care!
